import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import ProjectCard from "../components/Projects/ProjectCard";
import Particle from "../components/Particle";
import lbc from '..//assets/projects/lbc.svg'


const Projects = () => {
  return (
    <Container fluid className="project-section">
      <Particle />
      <Container>
        <h1 className="project-heading">
          My <strong className="yellow">Works </strong>
        </h1>
        <p style={{ color: "white" }}>
         I dont have a lot of works yet(,
         <br /> but here are some of them.
        </p>
        <Row style={{ justifyContent: "center", paddingBottom: "10px" }}>
          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={lbc}
              isBlog={false}
              title="LBC"
              description="A startup platform for language learning. Users are given the opportunity to learn a language by using cards that are generated by an AI model and checked by linguist administrators. The frontend is written using React, and MobX is used for state management. The backend is written in Node.js. For the database, we use MySQL with Sequelize as the ORM. The database is hosted on DigitalOcean."
              ghLink="https://github.com/WastedSwl/LBC.git"
            />
          </Col>

          {/* <Col md={4} className="project-card">
            <ProjectCard
              imgPath={project}
              isBlog={false}
              title="Social Media"
              description="This platform features a responsive interface built with Reactjs and CSS, allowing users to easily manage their profiles and posts through CRUD activities. The option to follow other users and interact with their posts (like or dislike) is also available, with suggestions for new users to follow. Users can only view posts from their followed users and can only engage in chat with those they follow. The backend is powered by Nodejs and Expressjs server, while MongoDB is utilized as the database."
              ghLink="https://github.com/19sajib/social-media"
            />
          </Col> */}

         
        </Row>
      </Container>
    </Container>
  )
}

export default Projects